services:
  sublinkx:
    image: ghcr.io/hbsx/sublinkx:latest
    pull_policy: always
    container_name: sublinkx
    ports:
      - "8000:8000"
    volumes:
      - ./data/db:/app/db
      - ./data/template:/app/template
      - ./data/logs:/app/logs
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped
    init: true
    stop_grace_period: 10s
